@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@Authorization=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuadjuWbmyIsInN1YiI6MywiaWF0IjoxNjEwODU0ODQ2LCJleHAiOjE2MTA4NTQ4NzZ9.MFgOxdgpL6INkP3xkUddfLgM-JCyUGG9cvOUBstE39o
POST {{host}}/auth/login 
Content-Type: {{contentType}}

{
  "username": "李四", 
  "password": "123"
}

###
GET {{host}}/user
Authorization:{{Authorization}}
###
GET {{host}}/user?ids=123&a=345

###
GET {{host}}/user/2
Authorization:{{Authorization}}

###
POST {{host}}/user 
Content-Type: {{contentType}}
Authorization:{{Authorization}}

{
    "username":"张三",
    "password":"123456",
     "age":20,
     "gender":"男"
}

### 
PUT {{host}}/user 
Content-Type: {{contentType}}
Authorization:{{Authorization}}

{
    "username":"李四",
    "password":"123",
    "id":3,
    "age":30,
    "gender":"男"
}

###
DELETE {{host}}/user/100
Authorization:{{Authorization}}
###

# PATCH https://{{host}}/authors/{{name}} HTTP/1.1
# Content-Type: {{contentType}}

# {
#     "content": "foo bar",
#     "created_at": "{{createdAt}}",
#     "modified_by": "{{modifiedBy}}"
# }