@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@Authorization=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOjEsImlhdCI6MTYxMDE3MzM5MiwiZXhwIjoxNjEwMTczNDUyfQ.eaftNb37Eq4kRLiJ5XZ-52iwTBxD07AixO7iegz_1n0
POST {{host}}/auth/login 
Content-Type: {{contentType}}

{
  "username": "john", 
  "password": "changeme"
}

###

GET {{host}}/profile
Authorization:{{Authorization}}
###
GET {{host}}/user

###
GET {{host}}/user?ids=123&a=345

###
GET {{host}}/user/100 

###
POST {{host}}/user 
Content-Type: {{contentType}}

{
    "name":"zs",
    "age":80,
    "gender":123
}

###

# PATCH https://{{host}}/authors/{{name}} HTTP/1.1
# Content-Type: {{contentType}}

# {
#     "content": "foo bar",
#     "created_at": "{{createdAt}}",
#     "modified_by": "{{modifiedBy}}"
# }